apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8070/eureka/"
