apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: user-service
    repo: ../../helm/microservice-rollout
    valuesFile: values.yaml
    releaseName: user-service
    namespace: prod
