{{- if .Values.canary.analysis.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Values.service.name }}-analysis
spec:
  metrics:
  - name: success-rate
    interval: 1m
    successCondition: result >= {{ .Values.canary.analysis.successRate }}
    failureLimit: 3
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring:9090
        query: |
          sum(rate(http_server_requests_seconds_count{service="{{ .Values.service.name }}",status!~"5.."}[2m])) 
          / 
          sum(rate(http_server_requests_seconds_count{service="{{ .Values.service.name }}"}[2m])) * 100
  
  - name: error-rate
    interval: 1m
    successCondition: result <= {{ .Values.canary.analysis.errorRate }}
    failureLimit: 3
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring:9090
        query: |
          sum(rate(http_server_requests_seconds_count{service="{{ .Values.service.name }}",status=~"5.."}[2m])) 
          / 
          sum(rate(http_server_requests_seconds_count{service="{{ .Values.service.name }}"}[2m])) * 100
  
  - name: latency-p95
    interval: 1m
    successCondition: result <= 2000
    failureLimit: 3
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring:9090
        query: |
          histogram_quantile(0.95, 
            sum(rate(http_server_requests_seconds_bucket{service="{{ .Values.service.name }}"}[2m])) by (le)
          ) * 1000
{{- end }}
